services:
  gtest_test_env:
    image: gtest_env:0.1
    # environment:
    #   - TZ=Europe/Netherlands
    build:
      context: .
      dockerfile: ContainerFile
      args:
        BUILD_DIR: /mnt/ws
        TIMEZONE: Europe/Berlin
        # Rebuild the container when GTest version is changed else the value has no effect
        GTEST_VERSION: v1.14.0
    stdin_open: true
    tty: true
    hostname: gtest_env
    privileged: false
    cap_add:
      - all

    entrypoint: /bin/bash 
    volumes:
      - type: bind
        source: ../
        target: /mnt/ws
        consistency: consistent
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"

      - type: bind
        source: ${HOME}/.container_bash_history
        target: /root/.bash_history

      - type: bind
        source: ${HOME}/.container_bashrc
        target: /root/.bashrc
